# Generated by Django 3.1.2 on 2020-11-04 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.business')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.datetime(2020, 11, 4, 20, 21, 5, 791437))),
                ('fulfillment_date', models.TimeField(default=datetime.datetime(2020, 11, 4, 20, 21, 5, 791461))),
                ('business', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.business')),
                ('customer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.customer')),
                ('offer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.business_offering')),
            ],
        ),
    ]
