# Generated by Django 3.1.2 on 2020-11-04 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_date',
            field=models.TimeField(default=datetime.datetime(2020, 11, 4, 20, 21, 16, 977605)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 20, 21, 16, 977582)),
        ),
    ]
