# Generated by Django 3.1.2 on 2020-10-18 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20201018_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.business'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.customer'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.business_offering'),
        ),
    ]
