# Generated by Django 3.1.2 on 2020-10-19 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20201018_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_date',
            field=models.TimeField(default=datetime.datetime(2020, 10, 19, 4, 9, 39, 977786)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 4, 9, 39, 977763)),
        ),
    ]
